# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Generated by CPANPLUS::Dist::Gentoo version 0.11

MODULE_AUTHOR="BSDZ"
inherit perl-module

S="${WORKDIR}/Tie-iCal-0.15"
DESCRIPTION="Tie iCal files to Perl hashes"
HOMEPAGE="http://search.cpan.org/dist/Tie-iCal"
SRC_URI="mirror://cpan/modules/by-authors/id/B/BS/BSDZ/Tie-iCal-0.15.tar.gz"
SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="amd64"
RDEPEND="dev-lang/perl
>=dev-perl/Tie-File-0.97
virtual/perl-ExtUtils-MakeMaker"
DEPEND="${RDEPEND}
>=virtual/perl-Module-Build-0.38"
SRC_TEST="do"
