# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Generated by CPANPLUS::Dist::Gentoo version 0.11

MODULE_AUTHOR="TODDR"
inherit perl-module

S="${WORKDIR}/Tie-File-0.98"
DESCRIPTION="Tie array to lines of a file"
HOMEPAGE="http://search.cpan.org/dist/Tie-File"
SRC_URI="mirror://cpan/modules/by-authors/id/T/TO/TODDR/Tie-File-0.98.tar.gz"
SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="amd64"
RDEPEND="dev-lang/perl
virtual/perl-ExtUtils-MakeMaker"
DEPEND="${RDEPEND}
virtual/perl-ExtUtils-MakeMaker"
SRC_TEST="do"
